/beta/target/setPolarizationAngle 180
/beta/toggleLuciteHodoscope noOptics
/beta/toggleForwardTracker  noOptics
/beta/gun/setEventType flat
/beta/gun/setEnergyMin 0.90
/beta/gun/setEnergyMax  4.0
/beta/gun/setThetaMin 36.0
/beta/gun/setThetaMax 44.0
/beta/gun/setPhiMin   -25.0
/beta/gun/setPhiMax   25.0
/beta/gun/refresh
/beta/gun/setParticle e-
/beta/gun/refresh
#/beta/gun/listPSVariables 
/beta/simulateTrigger 1

/run/beamOn 1000

