/beta/target/setPolarizationAngle 180
#/beta/toggleBigcal on
#/beta/toggleForwardTracker off
#/beta/toggleLuciteHodoscope off

/beta/gun/setEventType flat
/beta/gun/setEnergyMin 0.50
/beta/gun/setEnergyMax  4.0
/beta/gun/setThetaMin 30.0
/beta/gun/setThetaMax 50.0
/beta/gun/setPhiMin   -30.0
/beta/gun/setPhiMax    30.0
/beta/gun/refresh
/beta/gun/setParticle gamma 
/beta/simulateTrigger 0
/beta/gun/refresh
/beta/gun/listPSVariables 

/run/beamOn 100000
