//
// File generated by rootcint at Wed Mar 10 20:31:40 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "eventdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void rawBETAEvent_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_rawBETAEvent(void *p = 0);
   static void *newArray_rawBETAEvent(Long_t size, void *p);
   static void delete_rawBETAEvent(void *p);
   static void deleteArray_rawBETAEvent(void *p);
   static void destruct_rawBETAEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::rawBETAEvent*)
   {
      ::rawBETAEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::rawBETAEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("rawBETAEvent", ::rawBETAEvent::Class_Version(), "rawBETAEvent.h", 33,
                  typeid(::rawBETAEvent), DefineBehavior(ptr, ptr),
                  &::rawBETAEvent::Dictionary, isa_proxy, 0,
                  sizeof(::rawBETAEvent) );
      instance.SetNew(&new_rawBETAEvent);
      instance.SetNewArray(&newArray_rawBETAEvent);
      instance.SetDelete(&delete_rawBETAEvent);
      instance.SetDeleteArray(&deleteArray_rawBETAEvent);
      instance.SetDestructor(&destruct_rawBETAEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::rawBETAEvent*)
   {
      return GenerateInitInstanceLocal((::rawBETAEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::rawBETAEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *rawBETAEvent::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *rawBETAEvent::Class_Name()
{
   return "rawBETAEvent";
}

//______________________________________________________________________________
const char *rawBETAEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::rawBETAEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int rawBETAEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::rawBETAEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void rawBETAEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::rawBETAEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *rawBETAEvent::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::rawBETAEvent*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void rawBETAEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class rawBETAEvent.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> half_plate;
      R__b >> bgid;
      R__b >> bgtype;
      R__b >> btrigtype;
      R__b >> ngooda;
      R__b >> ngoodt;
      R__b >> ngoodta;
      R__b >> ngoodtt;
      R__b >> irowmax;
      R__b >> icolmax;
      R__b >> max_adc;
      R__b >> eventNumber;
      R__b >> analysisLevel;
      R__b >> triggerType;
      R__b >> tcharge;
      R__b >> charge2s;
      R__b >> tcharge_help;
      R__b >> charge2s_help;
      R__b >> tcharge_helm;
      R__b >> charge2s_helm;
      R__b >> polarea;
      R__b >> polarization;
      R__b >> hel_p_scaler;
      R__b >> hel_n_scaler;
      R__b >> hel_p_trig;
      R__b >> hel_n_trig;
      R__b >> dtime_p;
      R__b >> dtime_n;
      R__b >> gen_event_id_number;
      R__b >> gen_event_type;
      R__b >> gen_event_class;
      R__b >> gen_event_roc_summary;
      R__b >> gen_event_sequence_n;
      R__b.ReadStaticArray((int*)gen_event_trigtype);
      R__b >> T_trghms;
      R__b >> T_trgbig;
      R__b >> T_trgpi0;
      R__b >> T_trgbeta;
      R__b >> T_trgcoin1;
      R__b >> T_trgcoin2;
      R__b >> Bigcal_tdc_nhit;
      R__b.ReadStaticArray((int*)Bigcal_tdc_raw_igroup);
      R__b.ReadStaticArray((int*)Bigcal_tdc_raw_irow);
      R__b.ReadStaticArray((int*)Bigcal_tdc_raw);
      R__b >> Bigcal_prot_nhit;
      R__b.ReadStaticArray((int*)Bigcal_prot_ix);
      R__b.ReadStaticArray((int*)Bigcal_prot_iy);
      R__b.ReadStaticArray((int*)Bigcal_prot_adc_raw);
      R__b >> Bigcal_rcs_nhit;
      R__b.ReadStaticArray((int*)Bigcal_rcs_ix);
      R__b.ReadStaticArray((int*)Bigcal_rcs_iy);
      R__b.ReadStaticArray((int*)Bigcal_rcs_adc_raw);
      R__b >> Bigcal_atrig_nhit;
      R__b.ReadStaticArray((int*)Bigcal_atrig_igroup);
      R__b.ReadStaticArray((int*)Bigcal_atrig_ihalf);
      R__b.ReadStaticArray((int*)Bigcal_atrig_adc_raw);
      R__b >> Bigcal_ttrig_nhit;
      R__b.ReadStaticArray((int*)Bigcal_ttrig_igroup);
      R__b.ReadStaticArray((int*)Bigcal_ttrig_ihalf);
      R__b.ReadStaticArray((int*)Bigcal_ttrig_adc_raw);
      R__b >> y1t_hit;
      R__b.ReadStaticArray((int*)y1t_row);
      R__b.ReadStaticArray((int*)y1t_tdc);
      R__b.ReadStaticArray((double*)y1t_y);
      R__b >> y2t_hit;
      R__b.ReadStaticArray((int*)y2t_row);
      R__b.ReadStaticArray((int*)y2t_tdc);
      R__b.ReadStaticArray((double*)y2t_y);
      R__b >> x1t_hit;
      R__b.ReadStaticArray((int*)x1t_row);
      R__b.ReadStaticArray((int*)x1t_tdc);
      R__b.ReadStaticArray((double*)x1t_x);
      R__b >> cer_hit;
      R__b.ReadStaticArray((int*)cer_num);
      R__b.ReadStaticArray((int*)cer_tdc);
      R__b.ReadStaticArray((int*)cer_adcc);
      R__b >> ceradc_hit;
      R__b.ReadStaticArray((int*)ceradc_num);
      R__b.ReadStaticArray((int*)cer_adc);
      R__b >> luc_hit;
      R__b.ReadStaticArray((int*)luc_row);
      R__b.ReadStaticArray((int*)ladc_pos);
      R__b.ReadStaticArray((int*)ladc_neg);
      R__b.ReadStaticArray((int*)ltdc_pos);
      R__b.ReadStaticArray((int*)ltdc_neg);
      R__b.ReadStaticArray((double*)luc_y);
      R__b >> hms_p;
      R__b >> hms_e;
      R__b >> hms_theta;
      R__b >> hms_phi;
      R__b >> hsxfp_s;
      R__b >> hsyfp_s;
      R__b >> hsxpfp_s;
      R__b >> hsypfp_s;
      R__b >> hms_xtar;
      R__b >> hms_ytar;
      R__b >> hms_yptar;
      R__b >> hms_xptar;
      R__b >> hms_delta;
      R__b >> hms_start;
      R__b >> hsshtrk_s;
      R__b >> hsshsum_s;
      R__b >> hsbeta_s;
      R__b >> rast_x;
      R__b >> rast_y;
      R__b >> slow_rast_x;
      R__b >> slow_rast_y;
      R__b >> sem_x;
      R__b >> sem_y;
      R__b >> i_helicity;
      R__b >> hms_cer_npe1;
      R__b >> hms_cer_npe2;
      R__b >> hms_cer_adc1;
      R__b >> hms_cer_adc2;
      R__b >> mc_nhit_init;
      R__b.ReadStaticArray((double*)mc_xpos_init);
      R__b.ReadStaticArray((double*)mc_ypos_init);
      R__b.ReadStaticArray((double*)mc_zpos_init);
      R__b.ReadStaticArray((double*)mc_theta_init);
      R__b.ReadStaticArray((double*)mc_phi_init);
      R__b.ReadStaticArray((double*)mc_e_init);
      R__b.ReadStaticArray((double*)mc_pid_init);
      R__b >> mc_nhit_bcplane;
      R__b.ReadStaticArray((double*)mc_x_bcplane);
      R__b.ReadStaticArray((double*)mc_y_bcplane);
      R__b.ReadStaticArray((double*)mc_pid_bcplane);
      R__b.ReadStaticArray((double*)mc_phi_bcplane);
      R__b.ReadStaticArray((double*)mc_theta_bcplane);
      R__b.ReadStaticArray((double*)mc_e_bcplane);
      R__b.ReadStaticArray((double*)mc_xmom_bcplane);
      R__b.ReadStaticArray((double*)mc_ymom_bcplane);
      R__b.ReadStaticArray((double*)mc_zmom_bcplane);
      R__b.CheckByteCount(R__s, R__c, rawBETAEvent::IsA());
   } else {
      R__c = R__b.WriteVersion(rawBETAEvent::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << half_plate;
      R__b << bgid;
      R__b << bgtype;
      R__b << btrigtype;
      R__b << ngooda;
      R__b << ngoodt;
      R__b << ngoodta;
      R__b << ngoodtt;
      R__b << irowmax;
      R__b << icolmax;
      R__b << max_adc;
      R__b << eventNumber;
      R__b << analysisLevel;
      R__b << triggerType;
      R__b << tcharge;
      R__b << charge2s;
      R__b << tcharge_help;
      R__b << charge2s_help;
      R__b << tcharge_helm;
      R__b << charge2s_helm;
      R__b << polarea;
      R__b << polarization;
      R__b << hel_p_scaler;
      R__b << hel_n_scaler;
      R__b << hel_p_trig;
      R__b << hel_n_trig;
      R__b << dtime_p;
      R__b << dtime_n;
      R__b << gen_event_id_number;
      R__b << gen_event_type;
      R__b << gen_event_class;
      R__b << gen_event_roc_summary;
      R__b << gen_event_sequence_n;
      R__b.WriteArray(gen_event_trigtype, 12);
      R__b << T_trghms;
      R__b << T_trgbig;
      R__b << T_trgpi0;
      R__b << T_trgbeta;
      R__b << T_trgcoin1;
      R__b << T_trgcoin2;
      R__b << Bigcal_tdc_nhit;
      R__b.WriteArray(Bigcal_tdc_raw_igroup, 1792);
      R__b.WriteArray(Bigcal_tdc_raw_irow, 1792);
      R__b.WriteArray(Bigcal_tdc_raw, 1792);
      R__b << Bigcal_prot_nhit;
      R__b.WriteArray(Bigcal_prot_ix, 1024);
      R__b.WriteArray(Bigcal_prot_iy, 1024);
      R__b.WriteArray(Bigcal_prot_adc_raw, 1024);
      R__b << Bigcal_rcs_nhit;
      R__b.WriteArray(Bigcal_rcs_ix, 720);
      R__b.WriteArray(Bigcal_rcs_iy, 720);
      R__b.WriteArray(Bigcal_rcs_adc_raw, 720);
      R__b << Bigcal_atrig_nhit;
      R__b.WriteArray(Bigcal_atrig_igroup, 38);
      R__b.WriteArray(Bigcal_atrig_ihalf, 38);
      R__b.WriteArray(Bigcal_atrig_adc_raw, 38);
      R__b << Bigcal_ttrig_nhit;
      R__b.WriteArray(Bigcal_ttrig_igroup, 336);
      R__b.WriteArray(Bigcal_ttrig_ihalf, 336);
      R__b.WriteArray(Bigcal_ttrig_adc_raw, 336);
      R__b << y1t_hit;
      R__b.WriteArray(y1t_row, 100);
      R__b.WriteArray(y1t_tdc, 100);
      R__b.WriteArray(y1t_y, 100);
      R__b << y2t_hit;
      R__b.WriteArray(y2t_row, 100);
      R__b.WriteArray(y2t_tdc, 100);
      R__b.WriteArray(y2t_y, 100);
      R__b << x1t_hit;
      R__b.WriteArray(x1t_row, 100);
      R__b.WriteArray(x1t_tdc, 100);
      R__b.WriteArray(x1t_x, 100);
      R__b << cer_hit;
      R__b.WriteArray(cer_num, 50);
      R__b.WriteArray(cer_tdc, 50);
      R__b.WriteArray(cer_adcc, 50);
      R__b << ceradc_hit;
      R__b.WriteArray(ceradc_num, 15);
      R__b.WriteArray(cer_adc, 15);
      R__b << luc_hit;
      R__b.WriteArray(luc_row, 90);
      R__b.WriteArray(ladc_pos, 90);
      R__b.WriteArray(ladc_neg, 90);
      R__b.WriteArray(ltdc_pos, 90);
      R__b.WriteArray(ltdc_neg, 90);
      R__b.WriteArray(luc_y, 90);
      R__b << hms_p;
      R__b << hms_e;
      R__b << hms_theta;
      R__b << hms_phi;
      R__b << hsxfp_s;
      R__b << hsyfp_s;
      R__b << hsxpfp_s;
      R__b << hsypfp_s;
      R__b << hms_xtar;
      R__b << hms_ytar;
      R__b << hms_yptar;
      R__b << hms_xptar;
      R__b << hms_delta;
      R__b << hms_start;
      R__b << hsshtrk_s;
      R__b << hsshsum_s;
      R__b << hsbeta_s;
      R__b << rast_x;
      R__b << rast_y;
      R__b << slow_rast_x;
      R__b << slow_rast_y;
      R__b << sem_x;
      R__b << sem_y;
      R__b << i_helicity;
      R__b << hms_cer_npe1;
      R__b << hms_cer_npe2;
      R__b << hms_cer_adc1;
      R__b << hms_cer_adc2;
      R__b << mc_nhit_init;
      R__b.WriteArray(mc_xpos_init, 4);
      R__b.WriteArray(mc_ypos_init, 4);
      R__b.WriteArray(mc_zpos_init, 4);
      R__b.WriteArray(mc_theta_init, 4);
      R__b.WriteArray(mc_phi_init, 4);
      R__b.WriteArray(mc_e_init, 4);
      R__b.WriteArray(mc_pid_init, 4);
      R__b << mc_nhit_bcplane;
      R__b.WriteArray(mc_x_bcplane, 10);
      R__b.WriteArray(mc_y_bcplane, 10);
      R__b.WriteArray(mc_pid_bcplane, 10);
      R__b.WriteArray(mc_phi_bcplane, 10);
      R__b.WriteArray(mc_theta_bcplane, 10);
      R__b.WriteArray(mc_e_bcplane, 10);
      R__b.WriteArray(mc_xmom_bcplane, 10);
      R__b.WriteArray(mc_ymom_bcplane, 10);
      R__b.WriteArray(mc_zmom_bcplane, 10);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void rawBETAEvent::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class rawBETAEvent.
      TClass *R__cl = ::rawBETAEvent::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__parent, "fCurrent", &fCurrent);
      R__insp.Inspect(R__cl, R__parent, "half_plate", &half_plate);
      R__insp.Inspect(R__cl, R__parent, "bgid", &bgid);
      R__insp.Inspect(R__cl, R__parent, "bgtype", &bgtype);
      R__insp.Inspect(R__cl, R__parent, "btrigtype", &btrigtype);
      R__insp.Inspect(R__cl, R__parent, "ngooda", &ngooda);
      R__insp.Inspect(R__cl, R__parent, "ngoodt", &ngoodt);
      R__insp.Inspect(R__cl, R__parent, "ngoodta", &ngoodta);
      R__insp.Inspect(R__cl, R__parent, "ngoodtt", &ngoodtt);
      R__insp.Inspect(R__cl, R__parent, "irowmax", &irowmax);
      R__insp.Inspect(R__cl, R__parent, "icolmax", &icolmax);
      R__insp.Inspect(R__cl, R__parent, "max_adc", &max_adc);
      R__insp.Inspect(R__cl, R__parent, "eventNumber", &eventNumber);
      R__insp.Inspect(R__cl, R__parent, "analysisLevel", &analysisLevel);
      R__insp.Inspect(R__cl, R__parent, "triggerType", &triggerType);
      R__insp.Inspect(R__cl, R__parent, "tcharge", &tcharge);
      R__insp.Inspect(R__cl, R__parent, "charge2s", &charge2s);
      R__insp.Inspect(R__cl, R__parent, "tcharge_help", &tcharge_help);
      R__insp.Inspect(R__cl, R__parent, "charge2s_help", &charge2s_help);
      R__insp.Inspect(R__cl, R__parent, "tcharge_helm", &tcharge_helm);
      R__insp.Inspect(R__cl, R__parent, "charge2s_helm", &charge2s_helm);
      R__insp.Inspect(R__cl, R__parent, "polarea", &polarea);
      R__insp.Inspect(R__cl, R__parent, "polarization", &polarization);
      R__insp.Inspect(R__cl, R__parent, "hel_p_scaler", &hel_p_scaler);
      R__insp.Inspect(R__cl, R__parent, "hel_n_scaler", &hel_n_scaler);
      R__insp.Inspect(R__cl, R__parent, "hel_p_trig", &hel_p_trig);
      R__insp.Inspect(R__cl, R__parent, "hel_n_trig", &hel_n_trig);
      R__insp.Inspect(R__cl, R__parent, "dtime_p", &dtime_p);
      R__insp.Inspect(R__cl, R__parent, "dtime_n", &dtime_n);
      R__insp.Inspect(R__cl, R__parent, "gen_event_id_number", &gen_event_id_number);
      R__insp.Inspect(R__cl, R__parent, "gen_event_type", &gen_event_type);
      R__insp.Inspect(R__cl, R__parent, "gen_event_class", &gen_event_class);
      R__insp.Inspect(R__cl, R__parent, "gen_event_roc_summary", &gen_event_roc_summary);
      R__insp.Inspect(R__cl, R__parent, "gen_event_sequence_n", &gen_event_sequence_n);
      R__insp.Inspect(R__cl, R__parent, "gen_event_trigtype[12]", gen_event_trigtype);
      R__insp.Inspect(R__cl, R__parent, "T_trghms", &T_trghms);
      R__insp.Inspect(R__cl, R__parent, "T_trgbig", &T_trgbig);
      R__insp.Inspect(R__cl, R__parent, "T_trgpi0", &T_trgpi0);
      R__insp.Inspect(R__cl, R__parent, "T_trgbeta", &T_trgbeta);
      R__insp.Inspect(R__cl, R__parent, "T_trgcoin1", &T_trgcoin1);
      R__insp.Inspect(R__cl, R__parent, "T_trgcoin2", &T_trgcoin2);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_tdc_nhit", &Bigcal_tdc_nhit);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_tdc_raw_igroup[1792]", Bigcal_tdc_raw_igroup);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_tdc_raw_irow[1792]", Bigcal_tdc_raw_irow);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_tdc_raw[1792]", Bigcal_tdc_raw);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_prot_nhit", &Bigcal_prot_nhit);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_prot_ix[1024]", Bigcal_prot_ix);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_prot_iy[1024]", Bigcal_prot_iy);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_prot_adc_raw[1024]", Bigcal_prot_adc_raw);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_rcs_nhit", &Bigcal_rcs_nhit);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_rcs_ix[720]", Bigcal_rcs_ix);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_rcs_iy[720]", Bigcal_rcs_iy);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_rcs_adc_raw[720]", Bigcal_rcs_adc_raw);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_atrig_nhit", &Bigcal_atrig_nhit);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_atrig_igroup[38]", Bigcal_atrig_igroup);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_atrig_ihalf[38]", Bigcal_atrig_ihalf);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_atrig_adc_raw[38]", Bigcal_atrig_adc_raw);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_ttrig_nhit", &Bigcal_ttrig_nhit);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_ttrig_igroup[336]", Bigcal_ttrig_igroup);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_ttrig_ihalf[336]", Bigcal_ttrig_ihalf);
      R__insp.Inspect(R__cl, R__parent, "Bigcal_ttrig_adc_raw[336]", Bigcal_ttrig_adc_raw);
      R__insp.Inspect(R__cl, R__parent, "y1t_hit", &y1t_hit);
      R__insp.Inspect(R__cl, R__parent, "y1t_row[100]", y1t_row);
      R__insp.Inspect(R__cl, R__parent, "y1t_tdc[100]", y1t_tdc);
      R__insp.Inspect(R__cl, R__parent, "y1t_y[100]", y1t_y);
      R__insp.Inspect(R__cl, R__parent, "y2t_hit", &y2t_hit);
      R__insp.Inspect(R__cl, R__parent, "y2t_row[100]", y2t_row);
      R__insp.Inspect(R__cl, R__parent, "y2t_tdc[100]", y2t_tdc);
      R__insp.Inspect(R__cl, R__parent, "y2t_y[100]", y2t_y);
      R__insp.Inspect(R__cl, R__parent, "x1t_hit", &x1t_hit);
      R__insp.Inspect(R__cl, R__parent, "x1t_row[100]", x1t_row);
      R__insp.Inspect(R__cl, R__parent, "x1t_tdc[100]", x1t_tdc);
      R__insp.Inspect(R__cl, R__parent, "x1t_x[100]", x1t_x);
      R__insp.Inspect(R__cl, R__parent, "cer_hit", &cer_hit);
      R__insp.Inspect(R__cl, R__parent, "cer_num[50]", cer_num);
      R__insp.Inspect(R__cl, R__parent, "cer_tdc[50]", cer_tdc);
      R__insp.Inspect(R__cl, R__parent, "cer_adcc[50]", cer_adcc);
      R__insp.Inspect(R__cl, R__parent, "ceradc_hit", &ceradc_hit);
      R__insp.Inspect(R__cl, R__parent, "ceradc_num[15]", ceradc_num);
      R__insp.Inspect(R__cl, R__parent, "cer_adc[15]", cer_adc);
      R__insp.Inspect(R__cl, R__parent, "luc_hit", &luc_hit);
      R__insp.Inspect(R__cl, R__parent, "luc_row[90]", luc_row);
      R__insp.Inspect(R__cl, R__parent, "ladc_pos[90]", ladc_pos);
      R__insp.Inspect(R__cl, R__parent, "ladc_neg[90]", ladc_neg);
      R__insp.Inspect(R__cl, R__parent, "ltdc_pos[90]", ltdc_pos);
      R__insp.Inspect(R__cl, R__parent, "ltdc_neg[90]", ltdc_neg);
      R__insp.Inspect(R__cl, R__parent, "luc_y[90]", luc_y);
      R__insp.Inspect(R__cl, R__parent, "hms_p", &hms_p);
      R__insp.Inspect(R__cl, R__parent, "hms_e", &hms_e);
      R__insp.Inspect(R__cl, R__parent, "hms_theta", &hms_theta);
      R__insp.Inspect(R__cl, R__parent, "hms_phi", &hms_phi);
      R__insp.Inspect(R__cl, R__parent, "hsxfp_s", &hsxfp_s);
      R__insp.Inspect(R__cl, R__parent, "hsyfp_s", &hsyfp_s);
      R__insp.Inspect(R__cl, R__parent, "hsxpfp_s", &hsxpfp_s);
      R__insp.Inspect(R__cl, R__parent, "hsypfp_s", &hsypfp_s);
      R__insp.Inspect(R__cl, R__parent, "hms_xtar", &hms_xtar);
      R__insp.Inspect(R__cl, R__parent, "hms_ytar", &hms_ytar);
      R__insp.Inspect(R__cl, R__parent, "hms_yptar", &hms_yptar);
      R__insp.Inspect(R__cl, R__parent, "hms_xptar", &hms_xptar);
      R__insp.Inspect(R__cl, R__parent, "hms_delta", &hms_delta);
      R__insp.Inspect(R__cl, R__parent, "hms_start", &hms_start);
      R__insp.Inspect(R__cl, R__parent, "hsshtrk_s", &hsshtrk_s);
      R__insp.Inspect(R__cl, R__parent, "hsshsum_s", &hsshsum_s);
      R__insp.Inspect(R__cl, R__parent, "hsbeta_s", &hsbeta_s);
      R__insp.Inspect(R__cl, R__parent, "rast_x", &rast_x);
      R__insp.Inspect(R__cl, R__parent, "rast_y", &rast_y);
      R__insp.Inspect(R__cl, R__parent, "slow_rast_x", &slow_rast_x);
      R__insp.Inspect(R__cl, R__parent, "slow_rast_y", &slow_rast_y);
      R__insp.Inspect(R__cl, R__parent, "sem_x", &sem_x);
      R__insp.Inspect(R__cl, R__parent, "sem_y", &sem_y);
      R__insp.Inspect(R__cl, R__parent, "i_helicity", &i_helicity);
      R__insp.Inspect(R__cl, R__parent, "hms_cer_npe1", &hms_cer_npe1);
      R__insp.Inspect(R__cl, R__parent, "hms_cer_npe2", &hms_cer_npe2);
      R__insp.Inspect(R__cl, R__parent, "hms_cer_adc1", &hms_cer_adc1);
      R__insp.Inspect(R__cl, R__parent, "hms_cer_adc2", &hms_cer_adc2);
      R__insp.Inspect(R__cl, R__parent, "mc_nhit_init", &mc_nhit_init);
      R__insp.Inspect(R__cl, R__parent, "mc_xpos_init[4]", mc_xpos_init);
      R__insp.Inspect(R__cl, R__parent, "mc_ypos_init[4]", mc_ypos_init);
      R__insp.Inspect(R__cl, R__parent, "mc_zpos_init[4]", mc_zpos_init);
      R__insp.Inspect(R__cl, R__parent, "mc_theta_init[4]", mc_theta_init);
      R__insp.Inspect(R__cl, R__parent, "mc_phi_init[4]", mc_phi_init);
      R__insp.Inspect(R__cl, R__parent, "mc_e_init[4]", mc_e_init);
      R__insp.Inspect(R__cl, R__parent, "mc_pid_init[4]", mc_pid_init);
      R__insp.Inspect(R__cl, R__parent, "mc_nhit_bcplane", &mc_nhit_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_x_bcplane[10]", mc_x_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_y_bcplane[10]", mc_y_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_pid_bcplane[10]", mc_pid_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_phi_bcplane[10]", mc_phi_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_theta_bcplane[10]", mc_theta_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_e_bcplane[10]", mc_e_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_xmom_bcplane[10]", mc_xmom_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_ymom_bcplane[10]", mc_ymom_bcplane);
      R__insp.Inspect(R__cl, R__parent, "mc_zmom_bcplane[10]", mc_zmom_bcplane);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_rawBETAEvent(void *p) {
      return  p ? new(p) ::rawBETAEvent : new ::rawBETAEvent;
   }
   static void *newArray_rawBETAEvent(Long_t nElements, void *p) {
      return p ? new(p) ::rawBETAEvent[nElements] : new ::rawBETAEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_rawBETAEvent(void *p) {
      delete ((::rawBETAEvent*)p);
   }
   static void deleteArray_rawBETAEvent(void *p) {
      delete [] ((::rawBETAEvent*)p);
   }
   static void destruct_rawBETAEvent(void *p) {
      typedef ::rawBETAEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::rawBETAEvent

/********************************************************
* eventdict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableeventdict();

extern "C" void G__set_cpp_environmenteventdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("rawBETAEvent.h");
  G__cpp_reset_tagtableeventdict();
}
#include <new>
extern "C" int G__cpp_dllreveventdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* rawBETAEvent */
static int G__eventdict_507_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   rawBETAEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new rawBETAEvent[n];
     } else {
       p = new((void*) gvp) rawBETAEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new rawBETAEvent;
     } else {
       p = new((void*) gvp) rawBETAEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) rawBETAEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rawBETAEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) rawBETAEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      rawBETAEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((rawBETAEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rawBETAEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) rawBETAEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) rawBETAEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventdict_507_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) rawBETAEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__eventdict_507_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   rawBETAEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new rawBETAEvent(*(rawBETAEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef rawBETAEvent G__TrawBETAEvent;
static int G__eventdict_507_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (rawBETAEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((rawBETAEvent*) (soff+(sizeof(rawBETAEvent)*i)))->~G__TrawBETAEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (rawBETAEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((rawBETAEvent*) (soff))->~G__TrawBETAEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__eventdict_507_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   rawBETAEvent* dest = (rawBETAEvent*) G__getstructoffset();
   *dest = *(rawBETAEvent*) libp->para[0].ref;
   const rawBETAEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* rawBETAEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunceventdict {
 public:
  G__Sizep2memfunceventdict(): p(&G__Sizep2memfunceventdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunceventdict::*p)();
};

size_t G__get_sizep2memfunceventdict()
{
  G__Sizep2memfunceventdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceeventdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent))) {
     rawBETAEvent *G__Lderived;
     G__Lderived=(rawBETAEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent),G__get_linked_tagnum(&G__eventdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableeventdict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__eventdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__eventdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__eventdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__eventdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__eventdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* rawBETAEvent */
static void G__setup_memvarrawBETAEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent));
   { rawBETAEvent *p; p=(rawBETAEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__eventdictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->fCurrent)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fCurrent=",0,"!current Tree number in a TChain");
   G__memvar_setup((void*)((long)(&p->half_plate)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"half_plate=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bgid)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"bgid=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bgtype)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"bgtype=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->btrigtype)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"btrigtype=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ngooda)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ngooda=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ngoodt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ngoodt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ngoodta)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ngoodta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ngoodtt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ngoodtt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->irowmax)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"irowmax=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->icolmax)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"icolmax=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->max_adc)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"max_adc=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->eventNumber)-(long)(p)),110,0,0,-1,G__defined_typename("Long64_t"),-1,1,"eventNumber=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->analysisLevel)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"analysisLevel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->triggerType)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"triggerType=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tcharge)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"tcharge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->charge2s)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"charge2s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tcharge_help)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"tcharge_help=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->charge2s_help)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"charge2s_help=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tcharge_helm)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"tcharge_helm=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->charge2s_helm)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"charge2s_helm=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->polarea)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"polarea=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->polarization)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"polarization=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hel_p_scaler)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"hel_p_scaler=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hel_n_scaler)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"hel_n_scaler=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hel_p_trig)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"hel_p_trig=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hel_n_trig)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"hel_n_trig=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtime_p)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dtime_p=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dtime_n)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"dtime_n=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gen_event_id_number)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gen_event_id_number=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gen_event_type)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gen_event_type=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gen_event_class)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gen_event_class=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gen_event_roc_summary)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gen_event_roc_summary=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gen_event_sequence_n)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gen_event_sequence_n=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->gen_event_trigtype)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"gen_event_trigtype[12]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T_trghms)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T_trghms=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T_trgbig)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T_trgbig=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T_trgpi0)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T_trgpi0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T_trgbeta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T_trgbeta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T_trgcoin1)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T_trgcoin1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->T_trgcoin2)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"T_trgcoin2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bigcal_tdc_nhit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_tdc_nhit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bigcal_tdc_raw_igroup)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_tdc_raw_igroup[1792]=",0,"[bigcal_tdc_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_tdc_raw_irow)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_tdc_raw_irow[1792]=",0,"[bigcal_tdc_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_tdc_raw)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_tdc_raw[1792]=",0,"[bigcal_tdc_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_prot_nhit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_prot_nhit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bigcal_prot_ix)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_prot_ix[1024]=",0,"[Bigcal_prot_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_prot_iy)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_prot_iy[1024]=",0,"[Bigcal_prot_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_prot_adc_raw)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_prot_adc_raw[1024]=",0,"[Bigcal_prot_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_rcs_nhit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_rcs_nhit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bigcal_rcs_ix)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_rcs_ix[720]=",0,"[Bigcal_rcs_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_rcs_iy)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_rcs_iy[720]=",0,"[Bigcal_rcs_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_rcs_adc_raw)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_rcs_adc_raw[720]=",0,"[Bigcal_rcs_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_atrig_nhit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_atrig_nhit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bigcal_atrig_igroup)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_atrig_igroup[38]=",0,"[Bigcal_atrig_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_atrig_ihalf)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_atrig_ihalf[38]=",0,"[Bigcal_atrig_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_atrig_adc_raw)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_atrig_adc_raw[38]=",0,"[Bigcal_atrig_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_ttrig_nhit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_ttrig_nhit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Bigcal_ttrig_igroup)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_ttrig_igroup[336]=",0,"[Bigcal_ttrig_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_ttrig_ihalf)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_ttrig_ihalf[336]=",0,"[Bigcal_ttrig_nhit]");
   G__memvar_setup((void*)((long)(&p->Bigcal_ttrig_adc_raw)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"Bigcal_ttrig_adc_raw[336]=",0,"[Bigcal_ttrig_nhit]");
   G__memvar_setup((void*)((long)(&p->y1t_hit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"y1t_hit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y1t_row)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"y1t_row[100]=",0,"[y1t_hit]");
   G__memvar_setup((void*)((long)(&p->y1t_tdc)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"y1t_tdc[100]=",0,"[y1t_hit]");
   G__memvar_setup((void*)((long)(&p->y1t_y)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"y1t_y[100]=",0,"[y1t_hit]");
   G__memvar_setup((void*)((long)(&p->y2t_hit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"y2t_hit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y2t_row)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"y2t_row[100]=",0,"[y2t_hit]");
   G__memvar_setup((void*)((long)(&p->y2t_tdc)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"y2t_tdc[100]=",0,"[y2t_hit]");
   G__memvar_setup((void*)((long)(&p->y2t_y)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"y2t_y[100]=",0,"[y2t_hit]");
   G__memvar_setup((void*)((long)(&p->x1t_hit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"x1t_hit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x1t_row)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"x1t_row[100]=",0,"[x1t_hit]");
   G__memvar_setup((void*)((long)(&p->x1t_tdc)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"x1t_tdc[100]=",0,"[x1t_hit]");
   G__memvar_setup((void*)((long)(&p->x1t_x)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"x1t_x[100]=",0,"[x1t_hit]");
   G__memvar_setup((void*)((long)(&p->cer_hit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"cer_hit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cer_num)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"cer_num[50]=",0,"[cer_hit]");
   G__memvar_setup((void*)((long)(&p->cer_tdc)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"cer_tdc[50]=",0,"[cer_hit]");
   G__memvar_setup((void*)((long)(&p->cer_adcc)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"cer_adcc[50]=",0,"[cer_hit]");
   G__memvar_setup((void*)((long)(&p->ceradc_hit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ceradc_hit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ceradc_num)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ceradc_num[15]=",0,"[ceradc_hit]");
   G__memvar_setup((void*)((long)(&p->cer_adc)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"cer_adc[15]=",0,"[ceradc_hit]");
   G__memvar_setup((void*)((long)(&p->luc_hit)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"luc_hit=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->luc_row)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"luc_row[90]=",0,"[luc_hit]");
   G__memvar_setup((void*)((long)(&p->ladc_pos)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ladc_pos[90]=",0,"[luc_hit]");
   G__memvar_setup((void*)((long)(&p->ladc_neg)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ladc_neg[90]=",0,"[luc_hit]");
   G__memvar_setup((void*)((long)(&p->ltdc_pos)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ltdc_pos[90]=",0,"[luc_hit]");
   G__memvar_setup((void*)((long)(&p->ltdc_neg)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"ltdc_neg[90]=",0,"[luc_hit]");
   G__memvar_setup((void*)((long)(&p->luc_y)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"luc_y[90]=",0,"[luc_hit]");
   G__memvar_setup((void*)((long)(&p->hms_p)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_p=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_e)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_e=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_theta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_theta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_phi)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_phi=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hsxfp_s)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hsxfp_s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hsyfp_s)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hsyfp_s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hsxpfp_s)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hsxpfp_s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hsypfp_s)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hsypfp_s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_xtar)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_xtar=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_ytar)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_ytar=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_yptar)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_yptar=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_xptar)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_xptar=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_delta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_delta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_start)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_start=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hsshtrk_s)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hsshtrk_s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hsshsum_s)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hsshsum_s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hsbeta_s)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hsbeta_s=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rast_x)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"rast_x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rast_y)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"rast_y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->slow_rast_x)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"slow_rast_x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->slow_rast_y)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"slow_rast_y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sem_x)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"sem_x=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sem_y)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"sem_y=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->i_helicity)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"i_helicity=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_cer_npe1)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_cer_npe1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_cer_npe2)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_cer_npe2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_cer_adc1)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_cer_adc1=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hms_cer_adc2)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"hms_cer_adc2=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_nhit_init)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mc_nhit_init=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_xpos_init)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_xpos_init[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_ypos_init)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_ypos_init[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_zpos_init)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_zpos_init[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_theta_init)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_theta_init[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_phi_init)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_phi_init[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_e_init)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_e_init[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_pid_init)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_pid_init[4]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_nhit_bcplane)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"mc_nhit_bcplane=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_x_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_x_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_y_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_y_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_pid_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_pid_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_phi_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_phi_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_theta_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_theta_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_e_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_e_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_xmom_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_xmom_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_ymom_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_ymom_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mc_zmom_bcplane)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"mc_zmom_bcplane[10]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__eventdictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvareventdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncrawBETAEvent(void) {
   /* rawBETAEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent));
   G__memfunc_setup("rawBETAEvent",1128,G__eventdict_507_0_1, 105, G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__eventdict_507_0_2, 85, G__get_linked_tagnum(&G__eventdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&rawBETAEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__eventdict_507_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rawBETAEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__eventdict_507_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&rawBETAEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__eventdict_507_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&rawBETAEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__eventdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__eventdict_507_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__eventdict_507_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rawBETAEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__eventdict_507_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&rawBETAEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__eventdict_507_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&rawBETAEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__eventdict_507_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&rawBETAEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("rawBETAEvent", 1128, G__eventdict_507_0_14, (int) ('i'), G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent), -1, 0, 1, 1, 1, 0, "u 'rawBETAEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~rawBETAEvent", 1254, G__eventdict_507_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__eventdict_507_0_16, (int) ('u'), G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent), -1, 1, 1, 1, 1, 0, "u 'rawBETAEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunceventdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaleventdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funceventdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__eventdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__eventdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__eventdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__eventdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__eventdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__eventdictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__eventdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__eventdictLN_rawBETAEvent = { "rawBETAEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableeventdict() {
  G__eventdictLN_TClass.tagnum = -1 ;
  G__eventdictLN_TBuffer.tagnum = -1 ;
  G__eventdictLN_TMemberInspector.tagnum = -1 ;
  G__eventdictLN_TObject.tagnum = -1 ;
  G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__eventdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__eventdictLN_TTree.tagnum = -1 ;
  G__eventdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__eventdictLN_rawBETAEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableeventdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__eventdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__eventdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__eventdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__eventdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__eventdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__eventdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__eventdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__eventdictLN_TTree);
   G__get_linked_tagnum_fwd(&G__eventdictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__eventdictLN_rawBETAEvent),sizeof(rawBETAEvent),-1,29952,(char*)NULL,G__setup_memvarrawBETAEvent,G__setup_memfuncrawBETAEvent);
}
extern "C" void G__cpp_setupeventdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupeventdict()");
  G__set_cpp_environmenteventdict();
  G__cpp_setup_tagtableeventdict();

  G__cpp_setup_inheritanceeventdict();

  G__cpp_setup_typetableeventdict();

  G__cpp_setup_memvareventdict();

  G__cpp_setup_memfunceventdict();
  G__cpp_setup_globaleventdict();
  G__cpp_setup_funceventdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunceventdict();
  return;
}
class G__cpp_setup_initeventdict {
  public:
    G__cpp_setup_initeventdict() { G__add_setup_func("eventdict",(G__incsetup)(&G__cpp_setupeventdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initeventdict() { G__remove_setup_func("eventdict"); }
};
G__cpp_setup_initeventdict G__cpp_setup_initializereventdict;

