# ----------------
# Verbose settings
# ----------------
#/control/verbose 0 
#/run/verbose 0 
#/tracking/verbose 0

# HepRepFile diriver
/vis/open HepRepFile

# OpenGL driver
#/vis/open OGLIX

# Add world volume
/vis/drawVolume

# Visualise geometry
/vis/viewer/flush

# Set camera angle for OGLIX driver
/vis/viewer/set/viewpointThetaPhi 70 120

# HandsOn 3: Trajectory visualisation
# Add trajectories to the visualization.
/vis/scene/add/trajectories

# Accumulate multiple events in one picture.
/vis/scene/endOfEventAction accumulate

# Trajectory colouring scheme
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set -1 blue
/vis/modeling/trajectories/drawByCharge-0/set 1 blue
/vis/modeling/trajectories/drawByCharge-0/set 0 red

#/vis/modeling/trajectories/create/drawByParticleID 
#/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton red
#/vis/modeling/trajectories/drawByParticleID-0/setRGBA e- 1 0 1 1
/run/beamOn 10 
