/vis/open OGLIX
/vis/scene/create bigcal
/vis/drawVolume 

#/vis/viewer/set/viewpointThetaPhi 70 20
#/vis/viewer/set/upThetaPhi 90 270
/vis/viewer/set/viewpointThetaPhi 30 0
/vis/viewer/set/upThetaPhi 90 0

/vis/scene/add/trajectories
/vis/scene/add/hits
#/vis/scene/endOfEventAction accumulate 5 

/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set -1 blue
/vis/modeling/trajectories/drawByCharge-0/set 1 blue
/vis/modeling/trajectories/drawByCharge-0/set 0 red

#/tracking/storeTrajectory 1 

/run/beamOn 10
/vis/enable 
/vis/reviewKeptEvents

/vis/viewer/flush
