#!/bin/bash
#
#   Request 1 processors on 1 node 
#
#PBS -q bigmem 
#   
#PBS -l nodes=1:ppn=1
#
#   Request 48 hours of walltime
#
#PBS -l walltime=48:00:00
#
#
#   Request 1 gigabyte of memory per process
#
#PBS -l pmem=3gb
#
#   Request that regular output and terminal output go to the same file
#
#PBS -j oe
#
#   The following is the body of the script. By default,
#   PBS scripts execute in your home directory, not the
#   directory from which they were submitted. The following
#   line places you in the directory from which the job
#   was submitted.
#
# cd $PBS_O_WORKDIR
cd $HOME/sane08/BETAG4/run
#
#   Now we want to run the program "hello".  "hello" is in
#   the directory that this script is being submitted from,
#   $PBS_O_WORKDIR.
#
echo " "
echo " "
echo "Job started on `hostname` at `date`"
echo " "

macfile=sane/para/para_500k_uniform_positron.mac
betag4_mac $macfile  & 
sleep 15


wait


echo " "
echo "Job Ended at `date`"
echo " "

