//
// File generated by rootcint at Mon Mar  1 01:55:12 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "geodict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void BIGCALGeometryCalculator_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_BIGCALGeometryCalculator(void *p);
   static void deleteArray_BIGCALGeometryCalculator(void *p);
   static void destruct_BIGCALGeometryCalculator(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::BIGCALGeometryCalculator*)
   {
      ::BIGCALGeometryCalculator *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::BIGCALGeometryCalculator >(0);
      static ::ROOT::TGenericClassInfo 
         instance("BIGCALGeometryCalculator", ::BIGCALGeometryCalculator::Class_Version(), "BIGCALGeometryCalculator.hh", 29,
                  typeid(::BIGCALGeometryCalculator), DefineBehavior(ptr, ptr),
                  &::BIGCALGeometryCalculator::Dictionary, isa_proxy, 0,
                  sizeof(::BIGCALGeometryCalculator) );
      instance.SetDelete(&delete_BIGCALGeometryCalculator);
      instance.SetDeleteArray(&deleteArray_BIGCALGeometryCalculator);
      instance.SetDestructor(&destruct_BIGCALGeometryCalculator);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::BIGCALGeometryCalculator*)
   {
      return GenerateInitInstanceLocal((::BIGCALGeometryCalculator*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::BIGCALGeometryCalculator*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *BIGCALGeometryCalculator::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *BIGCALGeometryCalculator::Class_Name()
{
   return "BIGCALGeometryCalculator";
}

//______________________________________________________________________________
const char *BIGCALGeometryCalculator::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::BIGCALGeometryCalculator*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int BIGCALGeometryCalculator::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::BIGCALGeometryCalculator*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void BIGCALGeometryCalculator::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::BIGCALGeometryCalculator*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *BIGCALGeometryCalculator::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::BIGCALGeometryCalculator*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void BIGCALGeometryCalculator::Streamer(TBuffer &R__b)
{
   // Stream an object of class BIGCALGeometryCalculator.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> rcsXSize;
      R__b >> rcsYSize;
      R__b >> protXSize;
      R__b >> protYSize;
      R__b >> rcsProtYSeparation;
      R__b >> rcsProtXSeparation;
      R__b >> rcsCellSize;
      R__b >> protCellSize;
      R__b >> rcsCellZSize;
      R__b >> protCellZSize;
      R__b >> bcVerticalOffset;
      R__b >> bcYSize;
      R__b >> bcXSize;
      R__b >> bigcalFace;
      R__b >> protNx;
      R__b >> protNy;
      R__b >> rcsNy;
      R__b >> rcsNx;
      R__b.ReadStaticArray((double*)cherenkovMirrorXSize);
      R__b.ReadStaticArray((double*)cherenkovMirrorYSize);
      R__b.ReadStaticArray((double*)cherenkovMirrorPositionX);
      R__b.ReadStaticArray((double*)cherenkovMirrorPositionY);
      R__b.ReadStaticArray((double*)bc_cc);
      R__b >> arcsCellSize;
      R__b >> aprotCellSize;
      R__b.CheckByteCount(R__s, R__c, BIGCALGeometryCalculator::IsA());
   } else {
      R__c = R__b.WriteVersion(BIGCALGeometryCalculator::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << rcsXSize;
      R__b << rcsYSize;
      R__b << protXSize;
      R__b << protYSize;
      R__b << rcsProtYSeparation;
      R__b << rcsProtXSeparation;
      R__b << rcsCellSize;
      R__b << protCellSize;
      R__b << rcsCellZSize;
      R__b << protCellZSize;
      R__b << bcVerticalOffset;
      R__b << bcYSize;
      R__b << bcXSize;
      R__b << bigcalFace;
      R__b << protNx;
      R__b << protNy;
      R__b << rcsNy;
      R__b << rcsNx;
      R__b.WriteArray(cherenkovMirrorXSize, 8);
      R__b.WriteArray(cherenkovMirrorYSize, 8);
      R__b.WriteArray(cherenkovMirrorPositionX, 8);
      R__b.WriteArray(cherenkovMirrorPositionY, 8);
      R__b.WriteArray(bc_cc, 1792);
      R__b << arcsCellSize;
      R__b << aprotCellSize;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void BIGCALGeometryCalculator::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class BIGCALGeometryCalculator.
      TClass *R__cl = ::BIGCALGeometryCalculator::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "rcsXSize", &rcsXSize);
      R__insp.Inspect(R__cl, R__parent, "rcsYSize", &rcsYSize);
      R__insp.Inspect(R__cl, R__parent, "protXSize", &protXSize);
      R__insp.Inspect(R__cl, R__parent, "protYSize", &protYSize);
      R__insp.Inspect(R__cl, R__parent, "rcsProtYSeparation", &rcsProtYSeparation);
      R__insp.Inspect(R__cl, R__parent, "rcsProtXSeparation", &rcsProtXSeparation);
      R__insp.Inspect(R__cl, R__parent, "rcsCellSize", &rcsCellSize);
      R__insp.Inspect(R__cl, R__parent, "protCellSize", &protCellSize);
      R__insp.Inspect(R__cl, R__parent, "rcsCellZSize", &rcsCellZSize);
      R__insp.Inspect(R__cl, R__parent, "protCellZSize", &protCellZSize);
      R__insp.Inspect(R__cl, R__parent, "bcVerticalOffset", &bcVerticalOffset);
      R__insp.Inspect(R__cl, R__parent, "bcYSize", &bcYSize);
      R__insp.Inspect(R__cl, R__parent, "bcXSize", &bcXSize);
      R__insp.Inspect(R__cl, R__parent, "bigcalFace", &bigcalFace);
      R__insp.Inspect(R__cl, R__parent, "protNx", &protNx);
      R__insp.Inspect(R__cl, R__parent, "protNy", &protNy);
      R__insp.Inspect(R__cl, R__parent, "rcsNy", &rcsNy);
      R__insp.Inspect(R__cl, R__parent, "rcsNx", &rcsNx);
      R__insp.Inspect(R__cl, R__parent, "cherenkovMirrorXSize[8]", cherenkovMirrorXSize);
      R__insp.Inspect(R__cl, R__parent, "cherenkovMirrorYSize[8]", cherenkovMirrorYSize);
      R__insp.Inspect(R__cl, R__parent, "cherenkovMirrorPositionX[8]", cherenkovMirrorPositionX);
      R__insp.Inspect(R__cl, R__parent, "cherenkovMirrorPositionY[8]", cherenkovMirrorPositionY);
      R__insp.Inspect(R__cl, R__parent, "bc_cc[1792]", bc_cc);
      R__insp.Inspect(R__cl, R__parent, "arcsCellSize", &arcsCellSize);
      R__insp.Inspect(R__cl, R__parent, "aprotCellSize", &aprotCellSize);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_BIGCALGeometryCalculator(void *p) {
      delete ((::BIGCALGeometryCalculator*)p);
   }
   static void deleteArray_BIGCALGeometryCalculator(void *p) {
      delete [] ((::BIGCALGeometryCalculator*)p);
   }
   static void destruct_BIGCALGeometryCalculator(void *p) {
      typedef ::BIGCALGeometryCalculator current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::BIGCALGeometryCalculator

/********************************************************
* geodict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablegeodict();

extern "C" void G__set_cpp_environmentgeodict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("BIGCALGeometryCalculator.hh");
  G__cpp_reset_tagtablegeodict();
}
#include <new>
extern "C" int G__cpp_dllrevgeodict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* BIGCALGeometryCalculator */
static int G__geodict_511_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) BIGCALGeometryCalculator::GetCalculator());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getProtCellX((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getProtCellY((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getRCSCellX((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getRCSCellY((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getRCSCellX_BCCoords((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getRCSCellY_BCCoords((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getProtCellX_BCCoords((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getProtCellY_BCCoords((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getBlockXij_BCCoords((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((BIGCALGeometryCalculator*) G__getstructoffset())->getBlockYij_BCCoords((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) BIGCALGeometryCalculator::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BIGCALGeometryCalculator::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) BIGCALGeometryCalculator::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      BIGCALGeometryCalculator::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((BIGCALGeometryCalculator*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BIGCALGeometryCalculator::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BIGCALGeometryCalculator::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) BIGCALGeometryCalculator::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__geodict_511_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) BIGCALGeometryCalculator::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__geodict_511_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   BIGCALGeometryCalculator* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new BIGCALGeometryCalculator(*(BIGCALGeometryCalculator*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef BIGCALGeometryCalculator G__TBIGCALGeometryCalculator;
static int G__geodict_511_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (BIGCALGeometryCalculator*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((BIGCALGeometryCalculator*) (soff+(sizeof(BIGCALGeometryCalculator)*i)))->~G__TBIGCALGeometryCalculator();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (BIGCALGeometryCalculator*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((BIGCALGeometryCalculator*) (soff))->~G__TBIGCALGeometryCalculator();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__geodict_511_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   BIGCALGeometryCalculator* dest = (BIGCALGeometryCalculator*) G__getstructoffset();
   *dest = *(BIGCALGeometryCalculator*) libp->para[0].ref;
   const BIGCALGeometryCalculator& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* BIGCALGeometryCalculator */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncgeodict {
 public:
  G__Sizep2memfuncgeodict(): p(&G__Sizep2memfuncgeodict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncgeodict::*p)();
};

size_t G__get_sizep2memfuncgeodict()
{
  G__Sizep2memfuncgeodict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancegeodict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator))) {
     BIGCALGeometryCalculator *G__Lderived;
     G__Lderived=(BIGCALGeometryCalculator*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator),G__get_linked_tagnum(&G__geodictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablegeodict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__geodictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__geodictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__geodictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__geodictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__geodictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__geodictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__geodictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__geodictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__geodictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__geodictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__geodictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__geodictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__geodictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* BIGCALGeometryCalculator */
static void G__setup_memvarBIGCALGeometryCalculator(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator));
   { BIGCALGeometryCalculator *p; p=(BIGCALGeometryCalculator*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->rcsXSize)-(long)(p)),100,0,0,-1,-1,-1,1,"rcsXSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rcsYSize)-(long)(p)),100,0,0,-1,-1,-1,1,"rcsYSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protXSize)-(long)(p)),100,0,0,-1,-1,-1,1,"protXSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protYSize)-(long)(p)),100,0,0,-1,-1,-1,1,"protYSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rcsProtYSeparation)-(long)(p)),100,0,0,-1,-1,-1,1,"rcsProtYSeparation=",0,"center to center;");
   G__memvar_setup((void*)((long)(&p->rcsProtXSeparation)-(long)(p)),100,0,0,-1,-1,-1,1,"rcsProtXSeparation=",0,"horizontal displacement");
   G__memvar_setup((void*)((long)(&p->rcsCellSize)-(long)(p)),100,0,0,-1,-1,-1,1,"rcsCellSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protCellSize)-(long)(p)),100,0,0,-1,-1,-1,1,"protCellSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rcsCellZSize)-(long)(p)),100,0,0,-1,-1,-1,1,"rcsCellZSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protCellZSize)-(long)(p)),100,0,0,-1,-1,-1,1,"protCellZSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bcVerticalOffset)-(long)(p)),100,0,0,-1,-1,-1,1,"bcVerticalOffset=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bcYSize)-(long)(p)),100,0,0,-1,-1,-1,1,"bcYSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bcXSize)-(long)(p)),100,0,0,-1,-1,-1,1,"bcXSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bigcalFace)-(long)(p)),100,0,0,-1,-1,-1,1,"bigcalFace=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protNx)-(long)(p)),105,0,0,-1,-1,-1,1,"protNx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->protNy)-(long)(p)),105,0,0,-1,-1,-1,1,"protNy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rcsNy)-(long)(p)),105,0,0,-1,-1,-1,1,"rcsNy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->rcsNx)-(long)(p)),105,0,0,-1,-1,-1,1,"rcsNx=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cherenkovMirrorXSize)-(long)(p)),100,0,0,-1,-1,-1,1,"cherenkovMirrorXSize[8]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cherenkovMirrorYSize)-(long)(p)),100,0,0,-1,-1,-1,1,"cherenkovMirrorYSize[8]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cherenkovMirrorPositionX)-(long)(p)),100,0,0,-1,-1,-1,1,"cherenkovMirrorPositionX[8]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->cherenkovMirrorPositionY)-(long)(p)),100,0,0,-1,-1,-1,1,"cherenkovMirrorPositionY[8]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->bc_cc)-(long)(p)),100,0,0,-1,-1,-1,1,"bc_cc[1792]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator),-1,-2,4,"bcGeoCalcInstance=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"arcsCellSize=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"aprotCellSize=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__geodictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvargeodict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncBIGCALGeometryCalculator(void) {
   /* BIGCALGeometryCalculator */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator));
   G__memfunc_setup("GetCalculator",1322,G__geodict_511_0_1, 85, G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (BIGCALGeometryCalculator* (*)())(&BIGCALGeometryCalculator::GetCalculator) ), 0);
   G__memfunc_setup("getProtCellX",1213,G__geodict_511_0_2, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", "coords centered in protvino frame", (void*) NULL, 0);
   G__memfunc_setup("getProtCellY",1214,G__geodict_511_0_3, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getRCSCellX",1024,G__geodict_511_0_4, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", "coords centered in rcs frame", (void*) NULL, 0);
   G__memfunc_setup("getRCSCellY",1025,G__geodict_511_0_5, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getRCSCellX_BCCoords",1870,G__geodict_511_0_6, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", "coords centered in BC frame", (void*) NULL, 0);
   G__memfunc_setup("getRCSCellY_BCCoords",1871,G__geodict_511_0_7, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getProtCellX_BCCoords",2059,G__geodict_511_0_8, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", "coords centered in BC frame", (void*) NULL, 0);
   G__memfunc_setup("getProtCellY_BCCoords",2060,G__geodict_511_0_9, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBlockXij_BCCoords",1956,G__geodict_511_0_10, 100, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - i i - - 0 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBlockYij_BCCoords",1957,G__geodict_511_0_11, 100, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - i i - - 0 - j", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BIGCALGeometryCalculator",2296,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator), -1, 0, 0, 1, 4, 0, "", "Private so that it can  not be called", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__geodict_511_0_13, 85, G__get_linked_tagnum(&G__geodictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&BIGCALGeometryCalculator::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__geodict_511_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BIGCALGeometryCalculator::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__geodict_511_0_15, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&BIGCALGeometryCalculator::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__geodict_511_0_16, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&BIGCALGeometryCalculator::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__geodictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__geodict_511_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__geodict_511_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BIGCALGeometryCalculator::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__geodict_511_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&BIGCALGeometryCalculator::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__geodict_511_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&BIGCALGeometryCalculator::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__geodict_511_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&BIGCALGeometryCalculator::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("BIGCALGeometryCalculator", 2296, G__geodict_511_0_25, (int) ('i'), 
G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator), -1, 0, 1, 1, 1, 0, "u 'BIGCALGeometryCalculator' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~BIGCALGeometryCalculator", 2422, G__geodict_511_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__geodict_511_0_27, (int) ('u'), G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator), -1, 1, 1, 1, 1, 0, "u 'BIGCALGeometryCalculator' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncgeodict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalgeodict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcgeodict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__geodictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__geodictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__geodictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__geodictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__geodictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__geodictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__geodictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__geodictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__geodictLN_BIGCALGeometryCalculator = { "BIGCALGeometryCalculator" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablegeodict() {
  G__geodictLN_TClass.tagnum = -1 ;
  G__geodictLN_TBuffer.tagnum = -1 ;
  G__geodictLN_TMemberInspector.tagnum = -1 ;
  G__geodictLN_TObject.tagnum = -1 ;
  G__geodictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__geodictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__geodictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__geodictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__geodictLN_BIGCALGeometryCalculator.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablegeodict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__geodictLN_TClass);
   G__get_linked_tagnum_fwd(&G__geodictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__geodictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__geodictLN_TObject);
   G__get_linked_tagnum_fwd(&G__geodictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__geodictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__geodictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__geodictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__geodictLN_BIGCALGeometryCalculator),sizeof(BIGCALGeometryCalculator),-1,29952,(char*)NULL,G__setup_memvarBIGCALGeometryCalculator,G__setup_memfuncBIGCALGeometryCalculator);
}
extern "C" void G__cpp_setupgeodict(void) {
  G__check_setup_version(30051515,"G__cpp_setupgeodict()");
  G__set_cpp_environmentgeodict();
  G__cpp_setup_tagtablegeodict();

  G__cpp_setup_inheritancegeodict();

  G__cpp_setup_typetablegeodict();

  G__cpp_setup_memvargeodict();

  G__cpp_setup_memfuncgeodict();
  G__cpp_setup_globalgeodict();
  G__cpp_setup_funcgeodict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncgeodict();
  return;
}
class G__cpp_setup_initgeodict {
  public:
    G__cpp_setup_initgeodict() { G__add_setup_func("geodict",(G__incsetup)(&G__cpp_setupgeodict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initgeodict() { G__remove_setup_func("geodict"); }
};
G__cpp_setup_initgeodict G__cpp_setup_initializergeodict;

